import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NavItem from "@/components/NavItem";
import Navbar from "@/components/Navbar";
import { Briefcase, File, HandCoins, HomeIcon, Mail, User } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Navbar>
        <NavItem Icon={HomeIcon}>Home</NavItem>
        <NavItem Icon={User}>About</NavItem>
        <NavItem Icon={File}>Resume</NavItem>
        <NavItem Icon={Briefcase}>Portfolio</NavItem>
        <NavItem Icon={HandCoins}>Services</NavItem>
        <NavItem Icon={Mail}>Contact</NavItem>
      </Navbar>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
